feat(API): APIs for invitation links of Club Group
Computerization/Enspire pull request #536
Opened 2024-03-19 13:38 UTC by at-wr

Still a WIP

Related issue: #485

2024-03-21 14:03 UTC, qwerzl commented
Is it finished? If not, turn it into a draft and request a review from me once completed.

2024-03-25 08:59 UTC, at-wr commented
I guess that's it, might be enough for the API of this feature

2024-03-25 09:48 UTC, qwerzl requested changes

2024-03-25 09:48 UTC, qwerzl commented on db/schema.prisma
> +model JoinGroup {
rename to `GroupInfo`

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/club.get.ts
> +  club: z.string(),
z.number()

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/club.get.ts
> +    status: 'success',
I don't think we need to return this status

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/delete.delete.ts
> +  }).then(user => user?.tsimsStudentId)
```
(await prisma.user.findUnique({
    where: {
      id: auth.userId,
    },
  })).tsimsStudentId
```

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/club.get.ts
rename to /api/cas/info/get.get.ts

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/delete.delete.ts
Change to /api/cas/info/delete.delete.ts

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/delete.delete.ts
I don't think there is a use case for this `delete` endpoint.

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/new.post.ts
> +  }).then(club => club !== null)
Just find a club which has the given id and `presidentByTsimsStudentId === tsimsStudentId`.

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/new.post.ts
> +  }).then(club => club !== null)
If undefined, return 403.

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/update.post.ts
> +  }).then(club => club !== null)
As above

2024-03-25 09:48 UTC, qwerzl commented on types/api/cas/group/club.d.ts
I don't think we currently need this. The types of returned data from these endpoints are already given by prisma.

2024-03-25 09:48 UTC, qwerzl commented on server/api/cas/group/club.get.ts
> +    status: 'success',
Just return `joinGroup`, or `clubInfo` after the rename.

2024-03-26 15:10 UTC, merged